version: '3'
services:
  mongodb:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']
